NAME = libft.a

SRCS = ft_isalpha.c \
	   ft_isdigit.c \
	   ft_isalnum.c \
	   ft_isascii.c \
	   ft_isprint.c \
	   ft_tolower.c \
	   ft_toupper.c \
	   ft_strlen.c \
	   ft_strlcpy.c \
	   ft_strlcat.c \
	   ft_atoi.c \
	   ft_strchr.c \
	   ft_strrchr.c \
	   ft_strnstr.c \
	   ft_strncmp.c \
	   ft_memset.c \
	   ft_memcpy.c \
	   ft_bzero.c \
	   ft_memmove.c \
	   ft_memchr.c \
	   ft_memcmp.c \
	   ft_calloc.c \
	   ft_strdup.c \
	   ft_substr.c \
	   ft_strjoin.c \
	   ft_putchar_fd.c \
	   ft_putstr_fd.c \
	   ft_itoa.c \
	   ft_putnbr_fd.c \
	   ft_putendl_fd.c \
	   ft_strtrim.c \
	   ft_strmapi.c \
	   ft_striteri.c \
	   ft_split.c \

SRCSBONUS = ft_lstnew_bonus.c \
		    ft_lstadd_front_bonus.c \
			ft_lstsize_bonus.c \
			ft_lstlast_bonus.c


OBJS = ${SRCS:.c=.o}
OBJSBONUS = ${SRCSBONUS:.c=.o}
HEADER = libft.h


CC = gcc
RM = rm -f
CFLAGSS = -Wall -Wextra -Werror

.c.o: ${CC} ${CFLAGS} -I libft.h -c $< -o ${<:.c=.o}

all:		${NAME}

${NAME}:	${OBJS} ${HEADER}
			ar rcs ${NAME} ${OBJS}
			ranlib ${NAME}

bonus:		${OBJS} ${OBJSBONUS} ${HEADER}
			ar rcs ${NAME} ${OBJS} ${OBJSBONUS}
		   	@touch $@

clean:
			${RM} ${OBJS}

fclean:		clean
			${RM} ${NAME}

re:			fclean all

.PHONY:		all clean fclean re 
